services:
  - type: web
    name: greenl8site
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: DATABASE_URL
        value: postgresql://postgres:MHJDNikCqhnKtrmczOQZttUlWdzcDdRi@switchyard.proxy.rlwy.net:46150/railway
      - key: TOKEN_KEY
        value: "#g<*dnSC>wrr2V|Yk3o;VHa!wm'9^Z@M"
      - key: ADMIN_USERNAME
        value: greenl8
      - key: ADMIN_EMAIL
        value: judeasmith4@gmail.com
      - key: ADMIN_PASSWORD
        value: "doogan"
      - key: BASE_URL
        value: https://greenl8site.onrender.com 